import "@/../public/globals.css";
import "@/../public/main.scss";
import Header from "@/components/header";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Header />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
